# Site settings
title: Luke's home
email: lukeisme2013@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  学习，记录，思考的地方
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lukeisme.github.io" # the base hostname & protocol for your site
github_username:  Lukeisme

# Build settings
markdown: kramdown
